import type { Metadata } from "next";
import { geistMono, geistSans, instrumentSerif } from "./fonts";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} h-full antialiased`}
    >
      <ReactLenis root>
        <body className="min-h-full flex flex-col">{children}</body>
      </ReactLenis>
    </html>
  );
}
